sudo: required
services: 
    - docker
    
before_install:
    - docker build -t ngrieco/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true ngrieco/react-test npm run test
      #docker run -e CI=true USERNAME/react-test npm test -- --coverage
    
after_success:
    - docker build -t ngrieco/multi-client -f ./client ./client
    - docker build -t ngrieco/multi-nginx -f ./nginx ./nginx
    - docker build -t ngrieco/multi-server -f ./server ./server
    - docker build -t ngrieco/multi-worker -f ./worker ./worker
    # Log in in the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ngrieco/multi-client
    - docker push ngrieco/multi-nginx
    - docker push ngrieco/multi-server
    - docker push ngrieco/multi-worker
    